#include QMK_KEYBOARD_H

enum layer_number {
  _MAIN = 0,
  _QWERTY,
  _MEDIA,
  _OTHER,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [_MAIN] = LAYOUT(
KC_A,KC_B,KC_C,KC_D,KC_E,KC_F,KC_G,KC_H,KC_I,KC_J,KC_K,KC_L,KC_M,KC_N,KC_O,KC_P,KC_Q,KC_R,KC_S,KC_T,KC_U,KC_V,KC_W,KC_X,KC_Y),

    [_QWERTY] = LAYOUT(
KC_A,KC_B,KC_C,KC_D,KC_E,KC_F,KC_G,KC_H,KC_I,KC_J,KC_K,KC_L,KC_M,KC_N,KC_O,KC_P,KC_Q,KC_R,KC_S,KC_T,KC_U,KC_V,KC_W,KC_X,KC_Y),

    [_MEDIA] =
        LAYOUT(
KC_A,KC_B,KC_C,KC_D,KC_E,KC_F,KC_G,KC_H,KC_I,KC_J,KC_K,KC_L,KC_M,KC_N,KC_O,KC_P,KC_Q,KC_R,KC_S,KC_T,KC_U,KC_V,KC_W,KC_X,KC_Y),

    [_OTHER] =
        LAYOUT(
KC_A,KC_B,KC_C,KC_D,KC_E,KC_F,KC_G,KC_H,KC_I,KC_J,KC_K,KC_L,KC_M,KC_N,KC_O,KC_P,KC_Q,KC_R,KC_S,KC_T,KC_U,KC_V,KC_W,KC_X,KC_Y),
};
