#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(KC_MYCM, KC_PGDN, TG(1), TG(2), TG(3), KC_1, KC_2, KC_3, KC_4, KC_5, KC_F5, KC_F6, KC_F7, KC_F8, KC_SPC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, MS_BTN1, MS_BTN2, MS_BTN3, MS_BTN4, MS_BTN5),
    [1] = LAYOUT(KC_1, KC_2, KC_3, KC_TRNS, TG(0), KC_F13, KC_F14, KC_F15, KC_F16, KC_TRNS, KC_F17, KC_F18, KC_F19, KC_F20, KC_F21, KC_F22, KC_F23, KC_F24, KC_SPC, KC_ENT, MS_BTN1, MS_BTN2, MS_BTN3, MS_BTN4, MS_BTN5),
    [2] = LAYOUT(KC_MPRV, KC_MNXT, KC_MSTP, KC_MPLY, TG(0), KC_MYCM, KC_WREF, KC_1, KC_2, KC_3, KC_Q, KC_W, KC_E, KC_R, KC_TRNS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_Z, KC_X, KC_C, KC_SPC, KC_ENT),
    [3] = LAYOUT(KC_NUM, KC_PSLS, KC_PAST, KC_PMNS, TG(0), KC_P7, KC_P8, KC_P9, KC_PPLS, TG(1), KC_P4, KC_P5, KC_P6, KC_PCMM, TG(2), KC_P1, KC_P2, KC_P3, KC_PEQL, MS_BTN7, KC_P0, KC_PDOT, KC_PENT, KC_PDOT, MS_BTN8)
};



#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C
